# Config file for automatic testing at travis-ci.org
language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - pip install numpy
  - pip install python-dateutil
  - pip install scipy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
notifications: 
  email: false

# install the python script
install: 
  - pip install --use-mirrors commah

# command to run tests, e.g. python setup.py test
script: python setup.py test
