# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7_with_system_site_packages"

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: python setup.py test
