# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.7"
install:
  # Install conda
  - pip install conda
  # install deps
  - conda init
  - conda update conda --yes
  - deps='pip numpy scipy cosmolopy'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install your own package into the environment
  - sudo pip install commah
script:
  - python setup.py test
