language: python
dist: xenial
sudo: true
matrix:
    include:
        - python: 2.7
        - python: 3.5
        - python: 3.6
        - python: 3.7
install:
    - pip install --upgrade pip setuptools wheel
script:
    - pip install -r requirements_test.txt
    - pytest
notifications: 
    email: false
